채팅방 존재하지 않을 시 무한로딩 수정
ddit301/gaia pull request #229
Opened 2021-07-02 13:15 UTC by KrGil

2021-07-02 13:30 UTC, Shane-Park approved these changes
수고하셨습니다 !

2021-07-02 13:31 UTC, Shane-Park commented
제가 처가집에 와있어서 배포에 적용은 내일 점심 이후에 해볼게요 !

2021-07-03 10:40 UTC, Shane-Park requested changes
equals 한번 확인 해 주세요~ 수정 하고, 채팅 없을경우 화면 어떻게 나오는지 스샷 한개 남겨주세요 !

2021-07-03 10:40 UTC, Shane-Park commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			exists = ServiceResult.OK != result ? 0 : roomInfo.getChatroom_no();
이거 비교를 equals로 안하고 != 로 하셨네요!

2021-07-04 14:02 UTC, KrGil commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			exists = ServiceResult.OK != result ? 0 : roomInfo.getChatroom_no();
![image](https://user-images.githubusercontent.com/24990542/124377847-1dc6f180-dce9-11eb-9804-570e1b60ab41.png)

2021-07-08 03:02 UTC, Shane-Park requested changes
확인해주세요!

2021-07-08 03:02 UTC, ShanePark commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			roomInfo.setChatList(currentChat);
채팅방 생성이 안되었을 경우 처리가 전혀 안된 거 아닌가요? 171 번 라인 보면 exists에 0 혹은 채팅 방 번호를 넣도록 코드가 작성 되어 있는데, 채팅 방 생성이 안되었을 경우에도 roomInfo.getChatroom_no()를 사용하는데, 이경우에는 파라미터가 null로 넘어가서, currentChat이 null 이 될거고 roomInfo.chatList도 그럼 null이 될텐데 . 그래서 에러가 났던거고, roomInfo.chatroom_no이 null일 경우에 에러가 자꾸 나니깐 Thread로 슬립을 건 것 같은데 . 차라리 무조건 새로운 방이 만들어 져야 한다면 슬립 줄게 아니고 예외를 처리해야 하지 않을까요? sleep 500 거는순간, 해당 페이지에서는 기본적으로 500ms의 엄청난 response time이 일괄적으로 추가되는건데 이거 영 좋지 않을 것 같네요

2021-07-08 03:02 UTC, ShanePark commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
>  		result.put("mem_id", member.getMem_id());
서비스로 들어가야 할 로직들이 컨트롤러에 너무 많이 있어요. MVC 모델에 맞게 분리해주세요!

2021-07-08 03:27 UTC, KrGil commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			roomInfo.setChatList(currentChat);
1. 채팅방 생성이 안되었을 경우
- int exists = service.exists(mem_nos);
- if(exists==0) 여기서 걸러내요!!
- 그리고 생성 안되었을 때 
- if(chatRoom_no == roomInfo.getChatroom_no()) 여기서 null이면 걸려서 넘어가요!
- 이렇게 한 이유는 insert 된 방 번호만 항상 바로 조회하면 elastic에서 가지고오질 못하더라구요.

2. sleep을 사용한 이유는 chatroom_no때문이 아니라
- lateChat = service.getMessageListbyChatRoomOne(chatRoom_no, 1);
- 여기서 조회한 메시지가 elastic에 있는 채팅 내역을 조회하는건데 
- 그걸 insert와 거의 동시에 select를 하려고 하니까 데이터 전송 속도 때문인지 항상 받아오질 못하더라구요.

| 이걸 어떻게 알게 되었냐면
- debug 하니 값을 잘 받아오더라구요
- 그래서 생각해보니 debugging할때는  한줄할줄 compile 시키니까 시간이 걸려서 알게 되었어요!

결론 :
이게 insert와 select를 거의 동시에 진행해서 발생하는 문제인데
여기서 insert 후 select 하는 시간을 어떻게 미루는지가 관건인데 이게 sleep을 제외하고
다른 좋은 방법이 있을지 잘 모르겠어요!

2021-07-11 09:00 UTC, Shane-Park reviewed
한번 확인해주세요!

2021-07-11 09:00 UTC, ShanePark commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			roomInfo.setChatList(currentChat);
방금 생성한 방에서 채팅 내역을 왜 조회하죠 ? 채팅 내역이 없는게 정상 아닌가요?
굳이 아무 내용없는 대화 내역을 insert 할 필요가 없을 것 같습니다!

2021-07-11 09:00 UTC, ShanePark commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			roomInfo.setChatList(currentChat);
자꾸 여기저기 sleep이 들어가니깐 코드가 괜히 복잡해지고 점점 꼬이는 것 같아요. 
```
ServiceResult result = service.createChatRoom(roomInfo, mem_nos);
			if(ServiceResult.OK != result) exists=0;
```
이쪽 부분도 이상한게 serviceResult가 OK가 아니면, 그에 대한 예외 처리를 해줘서 어떻게든 방을 생성 시키거나, 혹은 결국 못만든다면  클라이언트 쪽에 방을 못만든 상황에 대해 설명을 해줘야 하는데 그게 아니고 exists = 0 걸고  넘어가버리는데 그럴거면 serviceResult를 체크하는게 의미 없지 않을까요?

2021-07-11 09:22 UTC, KrGil commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			roomInfo.setChatList(currentChat);
일단 첫 부분에서는 좌측 채팅방 리스트 조회할 때 가장 최근 채팅한 내역도 조회해야하는데 그럼 그건 어떻게 가지고올거죠?  insert를 안하게 되면 elastic에서 데이터가 없는데?? 그럼 그걸 아예 뺄까요?? 그럼 해결은 될탠데?

2021-07-11 09:22 UTC, KrGil commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			roomInfo.setChatList(currentChat);
그리고 sleep을 뺄거면 다른 방안이 있어야 할탠데 그 방안이 어떤게 있죠?? 저도 빼고 싶네요.

2021-07-11 09:31 UTC, KrGil commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			roomInfo.setChatList(currentChat);
ServiceResult result = service.createChatRoom(roomInfo, mem_nos);
			if(ServiceResult.OK != result) exists=0;
그리고 저 부분은 위에 보시면 빨간줄 쳐져있는데.... 작성된 부분을 다시 한번 확인해 보시길 바랍니다.

2021-07-11 12:08 UTC, Shane-Park commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			roomInfo.setChatList(currentChat);
일단 첫 부분에서는 좌측 채팅방 리스트 조회할 때 가장 최근 채팅한 내역도 조회해야하는데 그럼 그건 어떻게 가지고올거죠? insert를 안하게 되면 elastic에서 데이터가 없는데?? 그럼 그걸 아예 뺄까요?? 그럼 해결은 될탠데?
> 좌측에 채팅방 리스트 보여주는건 클라이언트 쪽에서 보여주기만 하면 되는거니깐, 그걸 굳이 데이터베이스에서 받아와서 보여주는게 아니고, 입력할때마다 렌더링만 해주면 됩니다. 비동기 요청시 평소 해왔던 것 처럼 하면 돼요.

2021-07-11 12:12 UTC, Shane-Park commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			roomInfo.setChatList(currentChat);
ServiceResult result = service.createChatRoom(roomInfo, mem_nos);
if(ServiceResult.OK != result) exists=0;
그리고 저 부분은 위에 보시면 빨간줄 쳐져있는데.... 작성된 부분을 다시 한번 확인해 보시길 바랍니다.
> 171번 라인 보시면 
```
exists = !ServiceResult.OK.equals(result) ? 0 : roomInfo.getChatroom_no(); 
```
exists 에 0 건다음에 exists 값 안써요

2021-07-11 12:26 UTC, Shane-Park commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			roomInfo.setChatList(currentChat);
지워진
```
if(ServiceResult.OK != result) exists=0;
```
랑, 새로 추가된
```
exists = !ServiceResult.OK.equals(result) ? 0 : roomInfo.getChatroom_no();
```
랑 결국 같은 코드에요. service.createChatRoom(roomInfo, mem_nos); 의 서비스 결과가 뭐가 나왔던 간에 아래 코드 진행에서는 결국 차이가 없습니다.

```
		if(exists==0) {
			// 새로운 채팅방 추가.
			ServiceResult result = service.createChatRoom(roomInfo, mem_nos);
			// 채팅방 생성여부 확인 후 잘 생성되었다면 채팅방 번호 넘기기  
			exists = !ServiceResult.OK.equals(result) ? 0 : roomInfo.getChatroom_no();
			// roomList에 채팅 내역 elastic에서 가지고와서 담기.(정렬시키기.)
			try {
				Thread.sleep(500);
				currentChat = service.getMessageListbyChatRoomOne(roomInfo.getChatroom_no(), 1);
			} catch (InterruptedException e) { e.printStackTrace(); }
			roomInfo.setChatList(currentChat);
		}
``` 
결국 이 안의 코드 흐름을 보면, 채팅방이 존재하지 않으면 채팅방 생성하는 서비스 실행 하고, 그 결과가 성공이든 실패든 간에 무조건 500ms 만큼 기다리고 나서 아무것도 없는 메시지 리스트 받아와서 roomInfo에 아무것도 없는 채팅 리스트 넣는 건데요.

sleep을 걸땐 걸더라도, 500ms 를 기다리면 그 기다리는데 투자한 sleep 시간 만큼 확실하게 받아온 걸 확인하는 코드를 넣거나, 아니면 반복문을 돌리면서 50ms 든 100ms 든 더 작은 시간을 sleep 하면서 서비스한 결과로 제대로 채팅 방이 생성 되었는지 확인 하는 코드를 넣든지 아니면
```
currentChat = service.getMessageListbyChatRoomOne(roomInfo.getChatroom_no(), 1);
```
이게 애초에 의미 없는 코드기 때문에, 아무것도 없는 채팅방에서 의미 없는 채팅 리스트 받느라 시간 쓰지 말고 채팅방 생성하는 로직이나 채팅방 목록 불러오는 로직을 변경 하면 해결 될 듯 합니다.

저는 여태 코드 클린하게 잘 작성해주시다가 갑자기 이번 문제 해결에서 주먹구구식으로 쓰여지는 것 같아서 다른 방법으로 해결 하셨으면 하는 마음이었는데.. 이 코드로 해당 이슈 마무리 지으시는게 편하시면 그대로 말씀해주시면 바로 merge 시키고 서버에 적용 시키겠습니다!

2021-07-11 15:07 UTC, KrGil commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			roomInfo.setChatList(currentChat);
일단 첫 부분에서는 좌측 채팅방 리스트 조회할 때 가장 최근 채팅한 내역도 조회해야하는데 그럼 그건 어떻게 가지고올거죠? insert를 안하게 되면 elastic에서 데이터가 없는데?? 그럼 그걸 아예 뺄까요?? 그럼 해결은 될탠데?

- 좌측에 채팅방 리스트 보여주는건 클라이언트 쪽에서 보여주기만 하면 되는거니깐, 그걸 굳이 데이터베이스에서 받아와서 보여주는게 아니고, 입력할때마다 렌더링만 해주면 됩니다. 비동기 요청시 평소 해왔던 것 처럼 하면 돼요.

- 이 부분은 이해가 잘 안가네요. 좌측의 채팅방 보여주는걸 db에서 안가지고오고 입력할때마다 렌더링믄 해주면 된다는게 무슨말인지 모르겠네요.

2021-07-11 23:35 UTC, Shane-Park commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			roomInfo.setChatList(currentChat);
좌측 채팅방 리스트에 방금 만든 새로운 채팅방이 보여야 하기 때문에 white space를 대화 내용으로 insert 해서 elastic search 에서 그 목록을 받아 온 후에 좌측 리스트에 보여주는 거라고 하셨는데, 
새로 만든 채팅방이 채팅방 목록에 보여지도록 하는 렌더링 과정을, 굳이 DB에서 받아와서 그 데이터를 토대로 화면을 그려줄 필요가 없이, 새로운 채팅방을 생성할 때 가지고 있는 모든 정보를 가지고 ( 새로운 채팅을 할 상대에 대한 정보, 새로 만들 방에 대한 정보-> 방에 대한 정보는 Elastic이 아니고 Oracle에서 가지고 오기 때문에 방을 생성할 때 이미 가지고 있음) 충분히 화면에 그려줄 수 있습니다. 또한 채팅방에서 내가 새로운 채팅을 입력 할 때, 좌측 채팅방 리스트의 최신 대화에 내가 쓴 대화가 보이도록 하는 내용이나 최근에 채팅을 입력한 대화방에 그 목록 중 최 상단으로 올라가게 하는 것 또한 굳이 DB를 거쳐서 한번 더 조회를 거치지 않고도 충분히 클라이언트 사이드에서만 javascript 만으로 구현이 가능 합니다.

2021-07-11 23:36 UTC, Shane-Park commented on gaia/src/main/java/best/gaia/chat/controller/ChatREST.java
> +			roomInfo.setChatList(currentChat);
일단 벌써 1주일 넘었고 하다 보니 merge 시키겠습니다

2021-07-11 23:37 UTC, merged