memberPage setting 수정 및 datasource-context.xml 수정
ddit301/gaia pull request #52
Opened 2021-05-25 14:29 UTC by KrGil

p:typeAliasesPackage="best.gaia.vo.**" ->  "best.gaia.**.vo"

2021-05-25 15:09 UTC, Shane-Park requested changes
내일 같이 코드보고 얘기좀 해봐요! 
제 생각에는
1. resultType에 alias 를 거는 것 보다 명확하게 패키지를 명시하는게 낫다고 생각하는데  어차피 코드어시스트도 되는데 클래스 이름만 써야 할 필요가 있을까요? 제가 알기론 저렇게 해도 컴퓨터에 따라 에러 메시지가 뜹니다. 한 컴퓨터에서라도 에러가 나서 거슬릴거라면 모두 패키지명을 기입해주는게 낫지 않을지
2. 제가 쓴건 아니지만 vo.**이 맞지 않을까요? vo 패키지에 하위 패키지가 생길 수 있단 전제 하에.
3. **.vo는 vo가 각기 다른 패키지에 있을 떄라 저희랑은 안맞는 듯 해요

2021-05-25 15:09 UTC, ShanePark commented on gaia/webapp/WEB-INF/spring/datasource-context.xml
> +		p:typeAliasesPackage="best.gaia.**.vo"
vo.**이 맞지 않을까요??

2021-05-25 15:09 UTC, ShanePark commented on gaia/src/main/resources/best/gaia/db/mybatis/mappers/member.xml
> +	<select id="selectUserList" resultType="MemberVo">
Vo 에서 o도 대문자로 되는게 맞지 않을까요?물론 대소문자 구분없이 잘 되긴 할겁니다

2021-05-25 15:09 UTC, ShanePark commented on gaia/webapp/resources/assets/custom_template/sidebar-member.jsp
> +// 		var url = '${cPath}/${mem_nick }'+ 'aa';
cPath 대신에 getContextPath()  쓰심 됩니다! prescript에 걸어두었습니다.

2021-05-26 00:13 UTC, KrGil commented
넵! 수정해서  commit 다시 할게요!!!

2021-05-26 01:20 UTC, Shane-Park approved these changes

2021-05-26 01:20 UTC, merged